// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt sql.NullTime
}

type Entry struct {
	ID        int64
	AccountID sql.NullInt64
	Amount    int64
	CreatedAt sql.NullTime
}

type Transfer struct {
	ID          int64
	FromAccount sql.NullInt64
	ToAccount   sql.NullInt64
	Amount      int64
	CreatedAt   sql.NullTime
}
